.\" Manpage for wol
.\" Contact iamrekcah @ github.com/iamrekcah for corrections.
.TH man 1 "18 June 2013" "0.8" "wol man page"
.SH NAME
wol - Wake-On-LAN client
.SH SYNOPSIS
Usage: wol [OPTION...] <mac address>

Wake-On-LAN packet sender

    -i, --interface=NAME       Specify the net interface to use
    -p, --password=PASSWORD    Specify the WOL password
    -q, -s, --quiet, --silent  No output
    -?, --help                 Give this help list
        --usage                Give a short usage message
    -V, --version              Print program version
.SH DESCRIPTION
wol is a command-line client for crafting and sending custom WOL Ethernet frames.
.SH OPTIONS
-i, --interface <IFACE>
    Select the interface through which to send the WOL-type Ethernet frame.

-p, --password <PASSWORD>
    Submit a password, which is sent in cleartext in the Ethernet frame, to the listening host. The password must be in the MAC-48 format (XX:XX:XX:XX:XX:XX where XX is a hexadecimal pair).

-v, --version
    Print the version number and exit.

-?, --help
    Print the help list.

--usage
    Print a short usage message.
.SH BUGS
No known bugs.
.SH AUTHOR
iamrekcah
